/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioShowRouteImport } from './routes/studio-show'
import { Route as SoldRouteImport } from './routes/sold'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as PrintsRouteImport } from './routes/prints'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BooksRouteImport } from './routes/books'
import { Route as AboutMeRouteImport } from './routes/about-me'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopSearchRouteImport } from './routes/shop.search'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as ProductCategoryPrintsRouteImport } from './routes/product-category.prints'
import { Route as ProductCategoryBooksRouteImport } from './routes/product-category.books'
import { Route as ProductCategoryHandleRouteImport } from './routes/product-category.$handle'
import { Route as LegalTermsOfServiceRouteImport } from './routes/legal.terms-of-service'
import { Route as LegalPrivacyPolicyRouteImport } from './routes/legal.privacy-policy'
import { Route as ShopPoliciesHandleRouteImport } from './routes/shop.policies.$handle'
import { Route as ShopPagesHandleRouteImport } from './routes/shop.pages.$handle'
import { Route as ShopCollectionsHandleRouteImport } from './routes/shop.collections.$handle'
import { Route as ProductCategoryAbstractAbstractAbstractRouteImport } from './routes/product-category.abstract.abstract-abstract'

const StudioShowRoute = StudioShowRouteImport.update({
  id: '/studio-show',
  path: '/studio-show',
  getParentRoute: () => rootRouteImport,
} as any)
const SoldRoute = SoldRouteImport.update({
  id: '/sold',
  path: '/sold',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintsRoute = PrintsRouteImport.update({
  id: '/prints',
  path: '/prints',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMeRoute = AboutMeRouteImport.update({
  id: '/about-me',
  path: '/about-me',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSearchRoute = ShopSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ShopRoute,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductCategoryPrintsRoute = ProductCategoryPrintsRouteImport.update({
  id: '/product-category/prints',
  path: '/product-category/prints',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductCategoryBooksRoute = ProductCategoryBooksRouteImport.update({
  id: '/product-category/books',
  path: '/product-category/books',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductCategoryHandleRoute = ProductCategoryHandleRouteImport.update({
  id: '/product-category/$handle',
  path: '/product-category/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsOfServiceRoute = LegalTermsOfServiceRouteImport.update({
  id: '/legal/terms-of-service',
  path: '/legal/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyPolicyRoute = LegalPrivacyPolicyRouteImport.update({
  id: '/legal/privacy-policy',
  path: '/legal/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopPoliciesHandleRoute = ShopPoliciesHandleRouteImport.update({
  id: '/policies/$handle',
  path: '/policies/$handle',
  getParentRoute: () => ShopRoute,
} as any)
const ShopPagesHandleRoute = ShopPagesHandleRouteImport.update({
  id: '/pages/$handle',
  path: '/pages/$handle',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCollectionsHandleRoute = ShopCollectionsHandleRouteImport.update({
  id: '/collections/$handle',
  path: '/collections/$handle',
  getParentRoute: () => ShopRoute,
} as any)
const ProductCategoryAbstractAbstractAbstractRoute =
  ProductCategoryAbstractAbstractAbstractRouteImport.update({
    id: '/product-category/abstract/abstract-abstract',
    path: '/product-category/abstract/abstract-abstract',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-me': typeof AboutMeRoute
  '/books': typeof BooksRoute
  '/contact': typeof ContactRoute
  '/contacts': typeof ContactsRoute
  '/prints': typeof PrintsRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sold': typeof SoldRoute
  '/studio-show': typeof StudioShowRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/product-category/$handle': typeof ProductCategoryHandleRoute
  '/product-category/books': typeof ProductCategoryBooksRoute
  '/product-category/prints': typeof ProductCategoryPrintsRoute
  '/product/$handle': typeof ProductHandleRoute
  '/shop/search': typeof ShopSearchRoute
  '/shop/': typeof ShopIndexRoute
  '/product-category/abstract/abstract-abstract': typeof ProductCategoryAbstractAbstractAbstractRoute
  '/shop/collections/$handle': typeof ShopCollectionsHandleRoute
  '/shop/pages/$handle': typeof ShopPagesHandleRoute
  '/shop/policies/$handle': typeof ShopPoliciesHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-me': typeof AboutMeRoute
  '/books': typeof BooksRoute
  '/contact': typeof ContactRoute
  '/contacts': typeof ContactsRoute
  '/prints': typeof PrintsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sold': typeof SoldRoute
  '/studio-show': typeof StudioShowRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/product-category/$handle': typeof ProductCategoryHandleRoute
  '/product-category/books': typeof ProductCategoryBooksRoute
  '/product-category/prints': typeof ProductCategoryPrintsRoute
  '/product/$handle': typeof ProductHandleRoute
  '/shop/search': typeof ShopSearchRoute
  '/shop': typeof ShopIndexRoute
  '/product-category/abstract/abstract-abstract': typeof ProductCategoryAbstractAbstractAbstractRoute
  '/shop/collections/$handle': typeof ShopCollectionsHandleRoute
  '/shop/pages/$handle': typeof ShopPagesHandleRoute
  '/shop/policies/$handle': typeof ShopPoliciesHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-me': typeof AboutMeRoute
  '/books': typeof BooksRoute
  '/contact': typeof ContactRoute
  '/contacts': typeof ContactsRoute
  '/prints': typeof PrintsRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sold': typeof SoldRoute
  '/studio-show': typeof StudioShowRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/product-category/$handle': typeof ProductCategoryHandleRoute
  '/product-category/books': typeof ProductCategoryBooksRoute
  '/product-category/prints': typeof ProductCategoryPrintsRoute
  '/product/$handle': typeof ProductHandleRoute
  '/shop/search': typeof ShopSearchRoute
  '/shop/': typeof ShopIndexRoute
  '/product-category/abstract/abstract-abstract': typeof ProductCategoryAbstractAbstractAbstractRoute
  '/shop/collections/$handle': typeof ShopCollectionsHandleRoute
  '/shop/pages/$handle': typeof ShopPagesHandleRoute
  '/shop/policies/$handle': typeof ShopPoliciesHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/about-me'
    | '/books'
    | '/contact'
    | '/contacts'
    | '/prints'
    | '/shop'
    | '/sitemap.xml'
    | '/sold'
    | '/studio-show'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/product-category/$handle'
    | '/product-category/books'
    | '/product-category/prints'
    | '/product/$handle'
    | '/shop/search'
    | '/shop/'
    | '/product-category/abstract/abstract-abstract'
    | '/shop/collections/$handle'
    | '/shop/pages/$handle'
    | '/shop/policies/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/about-me'
    | '/books'
    | '/contact'
    | '/contacts'
    | '/prints'
    | '/sitemap.xml'
    | '/sold'
    | '/studio-show'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/product-category/$handle'
    | '/product-category/books'
    | '/product-category/prints'
    | '/product/$handle'
    | '/shop/search'
    | '/shop'
    | '/product-category/abstract/abstract-abstract'
    | '/shop/collections/$handle'
    | '/shop/pages/$handle'
    | '/shop/policies/$handle'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/about-me'
    | '/books'
    | '/contact'
    | '/contacts'
    | '/prints'
    | '/shop'
    | '/sitemap.xml'
    | '/sold'
    | '/studio-show'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/product-category/$handle'
    | '/product-category/books'
    | '/product-category/prints'
    | '/product/$handle'
    | '/shop/search'
    | '/shop/'
    | '/product-category/abstract/abstract-abstract'
    | '/shop/collections/$handle'
    | '/shop/pages/$handle'
    | '/shop/policies/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AboutMeRoute: typeof AboutMeRoute
  BooksRoute: typeof BooksRoute
  ContactRoute: typeof ContactRoute
  ContactsRoute: typeof ContactsRoute
  PrintsRoute: typeof PrintsRoute
  ShopRoute: typeof ShopRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SoldRoute: typeof SoldRoute
  StudioShowRoute: typeof StudioShowRoute
  LegalPrivacyPolicyRoute: typeof LegalPrivacyPolicyRoute
  LegalTermsOfServiceRoute: typeof LegalTermsOfServiceRoute
  ProductCategoryHandleRoute: typeof ProductCategoryHandleRoute
  ProductCategoryBooksRoute: typeof ProductCategoryBooksRoute
  ProductCategoryPrintsRoute: typeof ProductCategoryPrintsRoute
  ProductHandleRoute: typeof ProductHandleRoute
  ProductCategoryAbstractAbstractAbstractRoute: typeof ProductCategoryAbstractAbstractAbstractRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio-show': {
      id: '/studio-show'
      path: '/studio-show'
      fullPath: '/studio-show'
      preLoaderRoute: typeof StudioShowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sold': {
      id: '/sold'
      path: '/sold'
      fullPath: '/sold'
      preLoaderRoute: typeof SoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prints': {
      id: '/prints'
      path: '/prints'
      fullPath: '/prints'
      preLoaderRoute: typeof PrintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-me': {
      id: '/about-me'
      path: '/about-me'
      fullPath: '/about-me'
      preLoaderRoute: typeof AboutMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/search': {
      id: '/shop/search'
      path: '/search'
      fullPath: '/shop/search'
      preLoaderRoute: typeof ShopSearchRouteImport
      parentRoute: typeof ShopRoute
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-category/prints': {
      id: '/product-category/prints'
      path: '/product-category/prints'
      fullPath: '/product-category/prints'
      preLoaderRoute: typeof ProductCategoryPrintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-category/books': {
      id: '/product-category/books'
      path: '/product-category/books'
      fullPath: '/product-category/books'
      preLoaderRoute: typeof ProductCategoryBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-category/$handle': {
      id: '/product-category/$handle'
      path: '/product-category/$handle'
      fullPath: '/product-category/$handle'
      preLoaderRoute: typeof ProductCategoryHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms-of-service': {
      id: '/legal/terms-of-service'
      path: '/legal/terms-of-service'
      fullPath: '/legal/terms-of-service'
      preLoaderRoute: typeof LegalTermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy-policy': {
      id: '/legal/privacy-policy'
      path: '/legal/privacy-policy'
      fullPath: '/legal/privacy-policy'
      preLoaderRoute: typeof LegalPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/policies/$handle': {
      id: '/shop/policies/$handle'
      path: '/policies/$handle'
      fullPath: '/shop/policies/$handle'
      preLoaderRoute: typeof ShopPoliciesHandleRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/pages/$handle': {
      id: '/shop/pages/$handle'
      path: '/pages/$handle'
      fullPath: '/shop/pages/$handle'
      preLoaderRoute: typeof ShopPagesHandleRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/collections/$handle': {
      id: '/shop/collections/$handle'
      path: '/collections/$handle'
      fullPath: '/shop/collections/$handle'
      preLoaderRoute: typeof ShopCollectionsHandleRouteImport
      parentRoute: typeof ShopRoute
    }
    '/product-category/abstract/abstract-abstract': {
      id: '/product-category/abstract/abstract-abstract'
      path: '/product-category/abstract/abstract-abstract'
      fullPath: '/product-category/abstract/abstract-abstract'
      preLoaderRoute: typeof ProductCategoryAbstractAbstractAbstractRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShopRouteChildren {
  ShopSearchRoute: typeof ShopSearchRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopCollectionsHandleRoute: typeof ShopCollectionsHandleRoute
  ShopPagesHandleRoute: typeof ShopPagesHandleRoute
  ShopPoliciesHandleRoute: typeof ShopPoliciesHandleRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopSearchRoute: ShopSearchRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopCollectionsHandleRoute: ShopCollectionsHandleRoute,
  ShopPagesHandleRoute: ShopPagesHandleRoute,
  ShopPoliciesHandleRoute: ShopPoliciesHandleRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AboutMeRoute: AboutMeRoute,
  BooksRoute: BooksRoute,
  ContactRoute: ContactRoute,
  ContactsRoute: ContactsRoute,
  PrintsRoute: PrintsRoute,
  ShopRoute: ShopRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SoldRoute: SoldRoute,
  StudioShowRoute: StudioShowRoute,
  LegalPrivacyPolicyRoute: LegalPrivacyPolicyRoute,
  LegalTermsOfServiceRoute: LegalTermsOfServiceRoute,
  ProductCategoryHandleRoute: ProductCategoryHandleRoute,
  ProductCategoryBooksRoute: ProductCategoryBooksRoute,
  ProductCategoryPrintsRoute: ProductCategoryPrintsRoute,
  ProductHandleRoute: ProductHandleRoute,
  ProductCategoryAbstractAbstractAbstractRoute:
    ProductCategoryAbstractAbstractAbstractRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
