/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoldRouteImport } from './routes/sold'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as BooksRouteImport } from './routes/books'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopSearchRouteImport } from './routes/shop.search'
import { Route as ShopCartRouteImport } from './routes/shop.cart'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as ProductCategoryHandleRouteImport } from './routes/product-category.$handle'
import { Route as LegalTermsOfServiceRouteImport } from './routes/legal.terms-of-service'
import { Route as LegalPrivacyPolicyRouteImport } from './routes/legal.privacy-policy'
import { Route as ShopPoliciesHandleRouteImport } from './routes/shop.policies.$handle'
import { Route as ShopPagesHandleRouteImport } from './routes/shop.pages.$handle'
import { Route as ShopCollectionsHandleRouteImport } from './routes/shop.collections.$handle'

const SoldRoute = SoldRouteImport.update({
  id: '/sold',
  path: '/sold',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSearchRoute = ShopSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ShopRoute,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductCategoryHandleRoute = ProductCategoryHandleRouteImport.update({
  id: '/product-category/$handle',
  path: '/product-category/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsOfServiceRoute = LegalTermsOfServiceRouteImport.update({
  id: '/legal/terms-of-service',
  path: '/legal/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyPolicyRoute = LegalPrivacyPolicyRouteImport.update({
  id: '/legal/privacy-policy',
  path: '/legal/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopPoliciesHandleRoute = ShopPoliciesHandleRouteImport.update({
  id: '/policies/$handle',
  path: '/policies/$handle',
  getParentRoute: () => ShopRoute,
} as any)
const ShopPagesHandleRoute = ShopPagesHandleRouteImport.update({
  id: '/pages/$handle',
  path: '/pages/$handle',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCollectionsHandleRoute = ShopCollectionsHandleRouteImport.update({
  id: '/collections/$handle',
  path: '/collections/$handle',
  getParentRoute: () => ShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/books': typeof BooksRoute
  '/shop': typeof ShopRouteWithChildren
  '/sold': typeof SoldRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/product-category/$handle': typeof ProductCategoryHandleRoute
  '/product/$handle': typeof ProductHandleRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/search': typeof ShopSearchRoute
  '/shop/': typeof ShopIndexRoute
  '/shop/collections/$handle': typeof ShopCollectionsHandleRoute
  '/shop/pages/$handle': typeof ShopPagesHandleRoute
  '/shop/policies/$handle': typeof ShopPoliciesHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/books': typeof BooksRoute
  '/sold': typeof SoldRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/product-category/$handle': typeof ProductCategoryHandleRoute
  '/product/$handle': typeof ProductHandleRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/search': typeof ShopSearchRoute
  '/shop': typeof ShopIndexRoute
  '/shop/collections/$handle': typeof ShopCollectionsHandleRoute
  '/shop/pages/$handle': typeof ShopPagesHandleRoute
  '/shop/policies/$handle': typeof ShopPoliciesHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/books': typeof BooksRoute
  '/shop': typeof ShopRouteWithChildren
  '/sold': typeof SoldRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/product-category/$handle': typeof ProductCategoryHandleRoute
  '/product/$handle': typeof ProductHandleRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/search': typeof ShopSearchRoute
  '/shop/': typeof ShopIndexRoute
  '/shop/collections/$handle': typeof ShopCollectionsHandleRoute
  '/shop/pages/$handle': typeof ShopPagesHandleRoute
  '/shop/policies/$handle': typeof ShopPoliciesHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/books'
    | '/shop'
    | '/sold'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/product-category/$handle'
    | '/product/$handle'
    | '/shop/cart'
    | '/shop/search'
    | '/shop/'
    | '/shop/collections/$handle'
    | '/shop/pages/$handle'
    | '/shop/policies/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/books'
    | '/sold'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/product-category/$handle'
    | '/product/$handle'
    | '/shop/cart'
    | '/shop/search'
    | '/shop'
    | '/shop/collections/$handle'
    | '/shop/pages/$handle'
    | '/shop/policies/$handle'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/books'
    | '/shop'
    | '/sold'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/product-category/$handle'
    | '/product/$handle'
    | '/shop/cart'
    | '/shop/search'
    | '/shop/'
    | '/shop/collections/$handle'
    | '/shop/pages/$handle'
    | '/shop/policies/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BooksRoute: typeof BooksRoute
  ShopRoute: typeof ShopRouteWithChildren
  SoldRoute: typeof SoldRoute
  LegalPrivacyPolicyRoute: typeof LegalPrivacyPolicyRoute
  LegalTermsOfServiceRoute: typeof LegalTermsOfServiceRoute
  ProductCategoryHandleRoute: typeof ProductCategoryHandleRoute
  ProductHandleRoute: typeof ProductHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sold': {
      id: '/sold'
      path: '/sold'
      fullPath: '/sold'
      preLoaderRoute: typeof SoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/search': {
      id: '/shop/search'
      path: '/search'
      fullPath: '/shop/search'
      preLoaderRoute: typeof ShopSearchRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/cart': {
      id: '/shop/cart'
      path: '/cart'
      fullPath: '/shop/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof ShopRoute
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-category/$handle': {
      id: '/product-category/$handle'
      path: '/product-category/$handle'
      fullPath: '/product-category/$handle'
      preLoaderRoute: typeof ProductCategoryHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms-of-service': {
      id: '/legal/terms-of-service'
      path: '/legal/terms-of-service'
      fullPath: '/legal/terms-of-service'
      preLoaderRoute: typeof LegalTermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy-policy': {
      id: '/legal/privacy-policy'
      path: '/legal/privacy-policy'
      fullPath: '/legal/privacy-policy'
      preLoaderRoute: typeof LegalPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/policies/$handle': {
      id: '/shop/policies/$handle'
      path: '/policies/$handle'
      fullPath: '/shop/policies/$handle'
      preLoaderRoute: typeof ShopPoliciesHandleRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/pages/$handle': {
      id: '/shop/pages/$handle'
      path: '/pages/$handle'
      fullPath: '/shop/pages/$handle'
      preLoaderRoute: typeof ShopPagesHandleRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/collections/$handle': {
      id: '/shop/collections/$handle'
      path: '/collections/$handle'
      fullPath: '/shop/collections/$handle'
      preLoaderRoute: typeof ShopCollectionsHandleRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface ShopRouteChildren {
  ShopCartRoute: typeof ShopCartRoute
  ShopSearchRoute: typeof ShopSearchRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopCollectionsHandleRoute: typeof ShopCollectionsHandleRoute
  ShopPagesHandleRoute: typeof ShopPagesHandleRoute
  ShopPoliciesHandleRoute: typeof ShopPoliciesHandleRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopCartRoute: ShopCartRoute,
  ShopSearchRoute: ShopSearchRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopCollectionsHandleRoute: ShopCollectionsHandleRoute,
  ShopPagesHandleRoute: ShopPagesHandleRoute,
  ShopPoliciesHandleRoute: ShopPoliciesHandleRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BooksRoute: BooksRoute,
  ShopRoute: ShopRouteWithChildren,
  SoldRoute: SoldRoute,
  LegalPrivacyPolicyRoute: LegalPrivacyPolicyRoute,
  LegalTermsOfServiceRoute: LegalTermsOfServiceRoute,
  ProductCategoryHandleRoute: ProductCategoryHandleRoute,
  ProductHandleRoute: ProductHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
