/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopSearchRouteImport } from './routes/shop.search'
import { Route as ShopCartRouteImport } from './routes/shop.cart'
import { Route as ShopProductsHandleRouteImport } from './routes/shop.products.$handle'
import { Route as ShopPoliciesHandleRouteImport } from './routes/shop.policies.$handle'
import { Route as ShopPagesHandleRouteImport } from './routes/shop.pages.$handle'
import { Route as ShopCollectionsHandleRouteImport } from './routes/shop.collections.$handle'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSearchRoute = ShopSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ShopRoute,
} as any)
const ShopProductsHandleRoute = ShopProductsHandleRouteImport.update({
  id: '/products/$handle',
  path: '/products/$handle',
  getParentRoute: () => ShopRoute,
} as any)
const ShopPoliciesHandleRoute = ShopPoliciesHandleRouteImport.update({
  id: '/policies/$handle',
  path: '/policies/$handle',
  getParentRoute: () => ShopRoute,
} as any)
const ShopPagesHandleRoute = ShopPagesHandleRouteImport.update({
  id: '/pages/$handle',
  path: '/pages/$handle',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCollectionsHandleRoute = ShopCollectionsHandleRouteImport.update({
  id: '/collections/$handle',
  path: '/collections/$handle',
  getParentRoute: () => ShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shop': typeof ShopRouteWithChildren
  '/shop/cart': typeof ShopCartRoute
  '/shop/search': typeof ShopSearchRoute
  '/shop/': typeof ShopIndexRoute
  '/shop/collections/$handle': typeof ShopCollectionsHandleRoute
  '/shop/pages/$handle': typeof ShopPagesHandleRoute
  '/shop/policies/$handle': typeof ShopPoliciesHandleRoute
  '/shop/products/$handle': typeof ShopProductsHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/search': typeof ShopSearchRoute
  '/shop': typeof ShopIndexRoute
  '/shop/collections/$handle': typeof ShopCollectionsHandleRoute
  '/shop/pages/$handle': typeof ShopPagesHandleRoute
  '/shop/policies/$handle': typeof ShopPoliciesHandleRoute
  '/shop/products/$handle': typeof ShopProductsHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/shop': typeof ShopRouteWithChildren
  '/shop/cart': typeof ShopCartRoute
  '/shop/search': typeof ShopSearchRoute
  '/shop/': typeof ShopIndexRoute
  '/shop/collections/$handle': typeof ShopCollectionsHandleRoute
  '/shop/pages/$handle': typeof ShopPagesHandleRoute
  '/shop/policies/$handle': typeof ShopPoliciesHandleRoute
  '/shop/products/$handle': typeof ShopProductsHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/shop'
    | '/shop/cart'
    | '/shop/search'
    | '/shop/'
    | '/shop/collections/$handle'
    | '/shop/pages/$handle'
    | '/shop/policies/$handle'
    | '/shop/products/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/shop/cart'
    | '/shop/search'
    | '/shop'
    | '/shop/collections/$handle'
    | '/shop/pages/$handle'
    | '/shop/policies/$handle'
    | '/shop/products/$handle'
  id:
    | '__root__'
    | '/'
    | '/shop'
    | '/shop/cart'
    | '/shop/search'
    | '/shop/'
    | '/shop/collections/$handle'
    | '/shop/pages/$handle'
    | '/shop/policies/$handle'
    | '/shop/products/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShopRoute: typeof ShopRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/search': {
      id: '/shop/search'
      path: '/search'
      fullPath: '/shop/search'
      preLoaderRoute: typeof ShopSearchRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/cart': {
      id: '/shop/cart'
      path: '/cart'
      fullPath: '/shop/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/products/$handle': {
      id: '/shop/products/$handle'
      path: '/products/$handle'
      fullPath: '/shop/products/$handle'
      preLoaderRoute: typeof ShopProductsHandleRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/policies/$handle': {
      id: '/shop/policies/$handle'
      path: '/policies/$handle'
      fullPath: '/shop/policies/$handle'
      preLoaderRoute: typeof ShopPoliciesHandleRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/pages/$handle': {
      id: '/shop/pages/$handle'
      path: '/pages/$handle'
      fullPath: '/shop/pages/$handle'
      preLoaderRoute: typeof ShopPagesHandleRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/collections/$handle': {
      id: '/shop/collections/$handle'
      path: '/collections/$handle'
      fullPath: '/shop/collections/$handle'
      preLoaderRoute: typeof ShopCollectionsHandleRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface ShopRouteChildren {
  ShopCartRoute: typeof ShopCartRoute
  ShopSearchRoute: typeof ShopSearchRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopCollectionsHandleRoute: typeof ShopCollectionsHandleRoute
  ShopPagesHandleRoute: typeof ShopPagesHandleRoute
  ShopPoliciesHandleRoute: typeof ShopPoliciesHandleRoute
  ShopProductsHandleRoute: typeof ShopProductsHandleRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopCartRoute: ShopCartRoute,
  ShopSearchRoute: ShopSearchRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopCollectionsHandleRoute: ShopCollectionsHandleRoute,
  ShopPagesHandleRoute: ShopPagesHandleRoute,
  ShopPoliciesHandleRoute: ShopPoliciesHandleRoute,
  ShopProductsHandleRoute: ShopProductsHandleRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShopRoute: ShopRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
